#!/bin/bash
#
# pedsignald    This shell script takes care of starting and stopping
#
# chkconfig: - 58 74
# description: pedsignal.

### BEGIN INIT INFO
# Provides: pedsignald
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Short-Description: start and stop pedsignal
# Descripton: pedsignald
### END INIT INFO

# Source function library.
. /etc/init.d/functions

prog=./pedsignal
lockfile=$prog.lock
pidfile=$prog.pid

OPTIONS="--daemonize --pidfile=$pidfile"

start() {
    [ -x $prog ] || exit 1 

        # Start daemons.
        echo -n $"Starting $prog: "
        daemon $prog $OPTIONS
    RETVAL=$?
        echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
        echo -n $"Shutting down $prog: "
    killproc $prog
    RETVAL=$?
        echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status $prog
    ;;
  restart|force-reload)
    stop
    start
    ;;
  try-restart|condrestart)
    if status $prog > /dev/null; then
        stop
        start
    fi
    ;;
  reload)
    exit 3
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|try-restart|force-reload}"
    exit 2
esac
